import { createContext, useContext, useState } from "react";

const translations = {
  mr: {
    Dashboard: "डॅशबोर्ड", "Demand Prediction": "मागणीचा अंदाज", "Sales Analytics": "विक्री विश्लेषण", "Udhaar / Khata": "उधार / खाते", Inventory: "साठा", "Inventory Planning": "साठा नियोजन", "Market Trends": "बाजारातील कल", "Forecast Reports": "अंदाज अहवाल", Alerts: "सूचना", Settings: "सेटिंग्ज", "Help & Support": "मदत आणि सहाय्य", "Did you know?": "तुम्हाला माहीत आहे का?", "Smarter Forecasts.": "अधिक अचूक अंदाज.", "Kirana Store": "किराणा दुकान", Logout: "बाहेर पडा", Refresh: "ताजे करा", "Welcome back,": "पुन्हा स्वागत आहे,", "Here's how your business is looking today.": "आज तुमच्या व्यवसायाची स्थिती अशी आहे.", "Your business at a glance — today's demand, stock, and AI forecast": "तुमच्या व्यवसायाची झलक — आजची मागणी, साठा आणि AI अंदाज", "AI-powered 7-day demand forecast with confidence intervals and prediction drivers": "विश्वास पातळी आणि मागणीचे कारणांसह ७ दिवसांचा AI अंदाज", "Predicted Demand (7d)": "अंदाजित मागणी (७ दिवस)", "Total Sales (7 days)": "एकूण विक्री (७ दिवस)", "Inventory in Hand": "हातातील साठा", "Stock-Out Risk": "साठा संपण्याचा धोका", products: "उत्पादने", product: "उत्पादन", units: "युनिट्स", unit: "युनिट", "Demand Prediction Overview": "मागणी अंदाजाचा आढावा", "Top Products": "आघाडीची उत्पादने", Actual: "प्रत्यक्ष", Predicted: "अंदाजित", "Inventory Status": "साठ्याची स्थिती", "Demand Forecast — Next 7 Days": "मागणीचा अंदाज — पुढील ७ दिवस", "Market Signals": "बाजार संकेत", "AI Recommendation": "AI शिफारस", "Forecast Accuracy": "अंदाजाची अचूकता", "How accurate are we?": "आपला अंदाज किती अचूक आहे?", "Backtest accuracy": "मागील चाचणीची अचूकता", "AI forecast": "AI अंदाज", "AI Demand Forecast": "AI मागणी अंदाज", "Peak Demand Day": "सर्वाधिक मागणीचा दिवस", "Recommended Reorder": "सुचवलेली पुनर्भरती", "Prediction Factors": "अंदाजाचे घटक", "Upcoming festival impact": "आगामी सणांचा परिणाम", "Model-derived demand uplift for this product": "या उत्पादनासाठी मॉडेलने दाखवलेली मागणीवाढ", "Affected products": "प्रभावित उत्पादने", "No upcoming festival signal in this forecast window.": "या अंदाजाच्या कालावधीत आगामी सणाचा संकेत नाही.", "Why this forecast? Key drivers and their impact level.": "हा अंदाज का? मुख्य कारणे आणि त्यांचा परिणाम.", "Alerts & Notifications": "सूचना आणि संदेश", "Open Alerts": "प्रलंबित सूचना", "High Priority": "उच्च प्राधान्य", Resolved: "निकाली काढले", "Stock Risk": "साठ्याचा धोका", "Alert Feed": "सूचना यादी", "Mark all read": "सर्व वाचलेले करा", Acknowledge: "मान्य करा", "Sending...": "पाठवत आहे...", "Send today's plan to WhatsApp": "आजची योजना WhatsApp वर पाठवा", "WhatsApp message sent": "WhatsApp संदेश पाठवला", "WhatsApp preview": "WhatsApp पूर्वदृश्य", Close: "बंद करा", "vs last week": "मागील आठवड्याच्या तुलनेत", "rolling month": "चालू महिना", "store orders": "दुकानाच्या ऑर्डर्स", "per invoice": "प्रति बिल", "active products": "सक्रिय उत्पादने", "watch closely": "लक्ष ठेवा", "urgent action": "तातडीची कृती", "across categories": "सर्व श्रेणींमध्ये", coverage: "कव्हरेज", "per category": "प्रति श्रेणी", "last 28 days": "मागील २८ दिवस", Optimal: "योग्य", "Low Stock": "कमी साठा", "Out of Stock": "साठा संपला", Overstock: "अति साठा", Active: "सक्रिय", Generated: "तयार", Pending: "प्रलंबित", Failed: "अयशस्वी", "Total Sales (7d)": "एकूण विक्री (७ दिवस)", "Sales 30d": "विक्री ३० दिवस", "Orders (7d)": "ऑर्डर्स (७ दिवस)", "Avg Order Value": "सरासरी ऑर्डर मूल्य", "Profit (7d)": "नफा (७ दिवस)", "Profit (30d)": "नफा (३० दिवस)", "Best-margin product": "सर्वाधिक मार्जिनचे उत्पादन", "Capital stuck in slow movers": "हळू विकल्या जाणाऱ्या साठ्यात अडकलेले भांडवल", "Dead stock / spoilage risk": "न वापरल्या जाणाऱ्या साठ्याचा धोका", "Sales velocity": "विक्रीचा वेग", "Stock value": "साठ्याचे मूल्य", "Daily Revenue Trend": "दैनंदिन उत्पन्नाचा कल", "Revenue by Category": "श्रेणीनुसार उत्पन्न", "Recent Transactions": "अलीकडील व्यवहार", Product: "उत्पादन", Date: "तारीख", Qty: "प्रमाण", Amount: "रक्कम", Payment: "पेमेंट", "Inventory Management": "साठा व्यवस्थापन", "Current stock health, coverage, and replenishment status": "सध्याची साठा स्थिती, कव्हरेज आणि पुनर्भरती", "Inventory Value": "साठ्याचे मूल्य", "Total SKUs": "एकूण SKU", "Stock Overview": "साठ्याचा आढावा", Category: "श्रेणी", Current: "सध्याचा", Ideal: "आदर्श", Safety: "सुरक्षा", Reorder: "पुनर्भरती", "Inventory Planning": "साठा नियोजन", "Recommended Production": "सुचवलेले उत्पादन", "Expected Demand": "अपेक्षित मागणी", "Shortfall SKUs": "कमतरता असलेले SKU", "Production Plan": "उत्पादन योजना", Demand: "मागणी", Target: "लक्ष्य", Production: "उत्पादन", Shortfall: "कमतरता", "Market Trends": "बाजारातील कल", "External demand and supply signals impacting pricing and stocking": "किंमत आणि साठ्यावर परिणाम करणारे बाह्य मागणी-पुरवठा संकेत", "Market Demand Index": "बाजार मागणी निर्देशांक", "Supply Index": "पुरवठा निर्देशांक", "Avg Price": "सरासरी किंमत", "Signals Tracked": "नोंदवलेले संकेत", "Category Trend Snapshot": "श्रेणी कलाचा आढावा", "Recent Market Signals": "अलीकडील बाजार संकेत", "Forecast Confidence": "अंदाजावरील विश्वास", "Products Forecasted": "अंदाज केलेली उत्पादने", "Next Run": "पुढील रन", "All Products — 7-Day Forecast Rank": "सर्व उत्पादने — ७ दिवसांचा अंदाज क्रम", "7-Day Forecast": "७ दिवसांचा अंदाज", "next 7 days": "पुढील ७ दिवस", "to meet demand + safety stock": "मागणी आणि सुरक्षा साठ्यासाठी", High: "उच्च", Medium: "मध्यम", Low: "कमी", "No forecast data yet.": "अजून अंदाजाचा डेटा नाही.", "Forecast not yet generated for this product.": "या उत्पादनाचा अंदाज अजून तयार झालेला नाही.",
    "Business Profile": "व्यवसाय प्रोफाइल", "Preferences": "प्राधान्ये", "Kirana Sahayak": "किराणा सहाय्यक", "Your shop assistant": "तुमचा दुकान सहाय्यक", "Ask me about stock, demand, or what to order this week.": "साठा, मागणी किंवा या आठवड्यात काय मागवायचे ते विचारा.", "Checking your shop data...": "तुमच्या दुकानाचा डेटा तपासत आहे...", "Ask Kirana Sahayak...": "किराणा सहाय्यकाला विचारा...",
    "Business name is required.": "व्यवसायाचे नाव आवश्यक आहे.", "Owner name is required.": "मालकाचे नाव आवश्यक आहे.", "Enter a valid 10-digit Indian mobile number starting with 6-9.": "६-९ ने सुरू होणारा १० अंकी भारतीय मोबाइल क्रमांक द्या.", "Enter a valid email address.": "वैध ईमेल पत्ता द्या.", "Password must be at least 8 characters with at least 1 letter and 1 number.": "पासवर्ड किमान ८ अक्षरांचा असावा आणि त्यात किमान १ अक्षर व १ अंक असावा.", "Business category is required.": "व्यवसायाचा प्रकार आवश्यक आहे.", "Location is required.": "ठिकाण आवश्यक आहे.", "Create Account": "खाते तयार करा", "Creating account...": "खाते तयार करत आहे...",
  },
  hi: {
    Dashboard: "डैशबोर्ड",
    "Demand Prediction": "मांग अनुमान",
    "Sales Analytics": "बिक्री विश्लेषण",
    "Udhaar / Khata": "उधार / खाता",
    Inventory: "इन्वेंटरी",
    "Inventory Planning": "इन्वेंटरी योजना",
    "Market Trends": "बाजार रुझान",
    "Forecast Reports": "पूर्वानुमान रिपोर्ट",
    Alerts: "अलर्ट",
    Settings: "सेटिंग्स",
    "Help & Support": "सहायता और समर्थन",
    "Did you know?": "क्या आपको पता है?",
    "Smarter Forecasts.": "बेहतर पूर्वानुमान।",
    "Kirana Store": "किराना दुकान",
    Logout: "लॉग आउट",
    Refresh: "रिफ्रेश",
    "Welcome back,": "वापसी पर स्वागत है,",
    "Here's how your business is looking today.": "आज आपके कारोबार की स्थिति ऐसी है।",
    "Your business at a glance — today's demand, stock, and AI forecast": "आपके कारोबार की झलक — आज की मांग, स्टॉक और AI पूर्वानुमान",
    "AI-powered 7-day demand forecast with confidence intervals and prediction drivers": "भरोसा स्तर और मांग के कारणों के साथ 7 दिन का AI मांग पूर्वानुमान",
    "Predicted Demand (7d)": "अनुमानित मांग (7 दिन)",
    "Total Sales (7 days)": "कुल बिक्री (7 दिन)",
    "Inventory in Hand": "उपलब्ध इन्वेंटरी",
    "Stock-Out Risk": "स्टॉक खत्म होने का जोखिम",
    products: "उत्पाद",
    product: "उत्पाद",
    units: "इकाइयां",
    unit: "इकाई",
    "Demand Prediction Overview": "मांग अनुमान अवलोकन",
    "Top Products": "शीर्ष उत्पाद",
    Actual: "वास्तविक",
    Predicted: "अनुमानित",
    "Inventory Status": "इन्वेंटरी स्थिति",
    "Demand Forecast — Next 7 Days": "मांग पूर्वानुमान — अगले 7 दिन",
    "Market Signals": "बाजार संकेत",
    "AI Recommendation": "AI सुझाव",
    "Forecast Accuracy": "पूर्वानुमान सटीकता",
    "How accurate are we?": "हम कितने सटीक हैं?",
    "Backtest accuracy": "बैकटेस्ट सटीकता",
    "Past predicted vs actual, with future confidence band": "पिछला अनुमान बनाम वास्तविक, भविष्य के भरोसा स्तर के साथ",
    "Not enough history for a backtest yet.": "बैकटेस्ट के लिए अभी पर्याप्त इतिहास नहीं है।",
    "AI forecast": "AI पूर्वानुमान",
    "AI Demand Forecast": "AI मांग पूर्वानुमान",
    "Peak Demand Day": "सबसे अधिक मांग का दिन",
    "Recommended Reorder": "अनुशंसित पुनः ऑर्डर",
    "Prediction Factors": "पूर्वानुमान कारक",
    "Upcoming festival impact": "आने वाले त्योहार का प्रभाव",
    "Model-derived demand uplift for this product": "इस उत्पाद के लिए मॉडल से निकली मांग वृद्धि",
    "Affected products": "प्रभावित उत्पाद",
    "No upcoming festival signal in this forecast window.": "इस पूर्वानुमान अवधि में आने वाले त्योहार का संकेत नहीं है।",
    "Why this forecast? Key drivers and their impact level.": "यह पूर्वानुमान क्यों? मुख्य कारण और उनका प्रभाव।",
    "Forecast accuracy": "पूर्वानुमान सटीकता",
    Model: "मॉडल",
    "Updated daily": "रोज अपडेट होता है",
    "Alerts & Notifications": "अलर्ट और सूचनाएं",
    "Open Alerts": "खुले अलर्ट",
    "High Priority": "उच्च प्राथमिकता",
    Resolved: "हल किए गए",
    "Stock Risk": "स्टॉक जोखिम",
    "Alert Feed": "अलर्ट सूची",
    "Mark all read": "सभी पढ़े हुए करें",
    Acknowledge: "स्वीकार करें",
    "Sending...": "भेज रहे हैं...",
    "Send today's plan to WhatsApp": "आज की योजना WhatsApp पर भेजें",
    "WhatsApp message sent": "WhatsApp संदेश भेज दिया गया",
    "WhatsApp preview": "WhatsApp पूर्वावलोकन",
    Close: "बंद करें",
    "vs last week": "पिछले सप्ताह की तुलना",
    "rolling month": "चलता महीना",
    "store orders": "दुकान के ऑर्डर",
    "per invoice": "प्रति बिल",
    "active products": "सक्रिय उत्पाद",
    "watch closely": "ध्यान से देखें",
    "urgent action": "तुरंत कार्रवाई",
    "across categories": "सभी श्रेणियों में",
    coverage: "कवरेज",
    "per category": "प्रति श्रेणी",
    "last 28 days": "पिछले 28 दिन",
    "Optimal": "सही स्तर",
    "Low Stock": "कम स्टॉक",
    "Out of Stock": "स्टॉक खत्म",
    Overstock: "अधिक स्टॉक",
    Active: "सक्रिय",
    Generated: "तैयार",
    Pending: "लंबित",
    Failed: "विफल",
    "Sales Analytics": "बिक्री विश्लेषण",
    "Historical sales performance, category mix, and transaction trends": "ऐतिहासिक बिक्री, श्रेणी मिश्रण और लेनदेन रुझान",
    "Total Sales (7d)": "कुल बिक्री (7 दिन)",
    "Sales 30d": "बिक्री 30 दिन",
    "Orders (7d)": "ऑर्डर (7 दिन)",
    "Avg Order Value": "औसत ऑर्डर मूल्य",
    "Profit (7d)": "लाभ (7 दिन)",
    "Profit (30d)": "लाभ (30 दिन)",
    "Best-margin product": "सबसे अच्छा मार्जिन उत्पाद",
    "Capital stuck in slow movers": "धीमी बिक्री वाले स्टॉक में फंसी पूंजी",
    "Dead stock / spoilage risk": "डेड स्टॉक / खराब होने का जोखिम",
    "Sales velocity": "बिक्री गति",
    "Stock value": "स्टॉक मूल्य",
    "Discount or bundle this stock to release capital.": "पूंजी निकालने के लिए इस स्टॉक पर छूट दें या बंडल बनाएं।",
    "revenue minus cost": "आय में से लागत घटाकर",
    "at-cost stock value": "लागत मूल्य पर स्टॉक",
    "High stock value with the lowest recent sales velocity": "कम हालिया बिक्री गति और अधिक स्टॉक मूल्य",
    "no sales yet": "अभी बिक्री नहीं",
    "since last sale": "पिछली बिक्री से",
    "Daily Revenue Trend": "दैनिक आय रुझान",
    "Revenue by Category": "श्रेणी के अनुसार आय",
    "Recent Transactions": "हाल के लेनदेन",
    Product: "उत्पाद",
    Date: "तारीख",
    Qty: "मात्रा",
    Amount: "राशि",
    Payment: "भुगतान",
    "Inventory Management": "इन्वेंटरी प्रबंधन",
    "Current stock health, coverage, and replenishment status": "वर्तमान स्टॉक स्थिति, कवरेज और भरपाई स्थिति",
    "Inventory Value": "इन्वेंटरी मूल्य",
    "Total SKUs": "कुल SKU",
    "Low Stock": "कम स्टॉक",
    "Out of Stock": "स्टॉक खत्म",
    "Stock Overview": "स्टॉक अवलोकन",
    "Coverage by product": "उत्पाद के अनुसार कवरेज",
    Category: "श्रेणी",
    Current: "वर्तमान",
    Ideal: "आदर्श",
    Safety: "सुरक्षा",
    Reorder: "पुनः ऑर्डर",
    "Inventory Planning": "इन्वेंटरी योजना",
    "Recommended production and reorder quantities for the next 7 days": "अगले 7 दिनों के लिए सुझाई गई उत्पादन और पुनः ऑर्डर मात्रा",
    "Recommended Production": "सुझाया गया उत्पादन",
    "Expected Demand": "अपेक्षित मांग",
    "Shortfall SKUs": "कम स्टॉक SKU",
    "Production Plan": "उत्पादन योजना",
    "Based on 7-day demand + safety stock": "7 दिन की मांग और सुरक्षा स्टॉक पर आधारित",
    Demand: "मांग",
    Target: "लक्ष्य",
    Production: "उत्पादन",
    Shortfall: "कमी",
    "Market Trends": "बाजार रुझान",
    "External demand and supply signals impacting pricing and stocking": "कीमत और स्टॉक को प्रभावित करने वाले बाहरी मांग और आपूर्ति संकेत",
    "Market Demand Index": "बाजार मांग सूचकांक",
    "Supply Index": "आपूर्ति सूचकांक",
    "Avg Price": "औसत मूल्य",
    "Signals Tracked": "ट्रैक किए गए संकेत",
    "Category Trend Snapshot": "श्रेणी रुझान झलक",
    "Recent Market Signals": "हाल के बाजार संकेत",
    "Forecast Reports": "पूर्वानुमान रिपोर्ट",
    "Generated summaries for operations, planning, and executive review": "परिचालन, योजना और समीक्षा के लिए तैयार सारांश",
    "Forecast Confidence": "पूर्वानुमान भरोसा",
    "Products Forecasted": "पूर्वानुमानित उत्पाद",
    "Next Run": "अगला रन",
    "Settings": "सेटिंग्स",
    "Alerts & Notifications": "अलर्ट और सूचनाएं",
    "Help & Support": "सहायता और समर्थन",
    "Last 28 days of actual sales + 7-day AI forecast with confidence band": "पिछले 28 दिनों की वास्तविक बिक्री + भरोसा स्तर के साथ 7 दिन का AI पूर्वानुमान",
    "Business name is required.": "व्यवसाय का नाम आवश्यक है।", "Owner name is required.": "मालिक का नाम आवश्यक है।", "Enter a valid 10-digit Indian mobile number starting with 6-9.": "6-9 से शुरू होने वाला 10 अंकों का भारतीय मोबाइल नंबर डालें।", "Enter a valid email address.": "मान्य ईमेल पता डालें।", "Password must be at least 8 characters with at least 1 letter and 1 number.": "पासवर्ड कम से कम 8 अक्षरों का हो और उसमें कम से कम 1 अक्षर और 1 अंक हो।", "Business category is required.": "व्यवसाय श्रेणी आवश्यक है।", "Location is required.": "स्थान आवश्यक है।", "Create Account": "खाता बनाएं", "Creating account...": "खाता बनाया जा रहा है...",
    "All Products — 7-Day Forecast Rank": "सभी उत्पाद — 7 दिन का पूर्वानुमान क्रम",
    "7-Day Forecast": "7 दिन का पूर्वानुमान",
    "next 7 days": "अगले 7 दिन",
    "to meet demand + safety stock": "मांग और सुरक्षा स्टॉक के लिए",
    High: "उच्च",
    Medium: "मध्यम",
    Low: "कम",
    "No forecast data yet.": "अभी कोई पूर्वानुमान डेटा नहीं है।",
    "Forecast not yet generated for this product.": "इस उत्पाद का पूर्वानुमान अभी तैयार नहीं है।",
    "Last 28 days of actual sales + 7-day AI forecast with confidence band": "पिछले 28 दिनों की वास्तविक बिक्री + भरोसा स्तर के साथ 7 दिन का AI पूर्वानुमान",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("kirana_language") || "en");
  const updateLanguage = (next) => {
    const value = typeof next === "function" ? next(language) : next;
    localStorage.setItem("kirana_language", value);
    setLanguage(value);
  };
  const t = (text) => translations[language]?.[text] || text;
  return <LanguageContext.Provider value={{ language, setLanguage: updateLanguage, t }}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);